FROM pdal/pdal:2.9.2

# Zorg dat RUN-commando's in de conda-base omgeving draaien
SHELL ["/bin/bash", "-lc"]

ENV DEBIAN_FRONTEND=noninteractive \
    MAMBA_DOCKERFILE_ACTIVATE=1

# Alles via conda + pip in de base environment
RUN conda install -y -c conda-forge \
      python=3.11 \
      numpy \
      pandas \
      pyarrow \
      laspy \
      pip \
    && pip install --no-cache-dir \
      opencv-python-headless \
      tqdm \
    && conda clean -afy

WORKDIR /app
